# Generated by Django 6.0.6 on 2026-06-09 09:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminConsumptionLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_daily_limit', models.IntegerField(default=0, help_text='0 means use profile default', verbose_name='Custom Daily Limit')),
                ('custom_monthly_limit', models.IntegerField(default=0, help_text='0 means use profile default', verbose_name='Custom Monthly Limit')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_limits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Consumption Limit',
                'verbose_name_plural': 'Admin Consumption Limits',
            },
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.CharField(max_length=500, verbose_name='Search Query')),
                ('results_count', models.IntegerField(default=0, verbose_name='Results Count')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Search Time')),
                ('duration', models.FloatField(default=0, help_text='Search duration in seconds', verbose_name='Duration (sec)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Search Log',
                'verbose_name_plural': 'Search Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_code', models.CharField(max_length=10, unique=True, verbose_name='National Code')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('phone_number', models.CharField(max_length=15, unique=True, verbose_name='Phone Number')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('daily_limit', models.IntegerField(default=10, help_text='Daily search limit', verbose_name='Daily Limit')),
                ('monthly_limit', models.IntegerField(default=300, help_text='Monthly search limit', verbose_name='Monthly Limit')),
                ('last_reset_daily', models.DateTimeField(default=django.utils.timezone.now, help_text='Last daily reset time', verbose_name='Last Daily Reset')),
                ('last_reset_monthly', models.DateTimeField(default=django.utils.timezone.now, help_text='Last monthly reset time', verbose_name='Last Monthly Reset')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
